name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Trigger on pushes to the master branch
  pull_request:
    branches:
      - master   # Trigger on pull requests to the master branch

jobs:
  # Frontend Job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # - name: Set up Node.js (Frontend)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.11.1'   # Update Node.js version here

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: |
          npm install

      - name: Run Linting (Frontend)
        working-directory: ./frontend
        run: |
          npm run lint

      - name: Run Tests (Frontend)
        working-directory: ./frontend
        run: |
          npm run test:coverage

      - name: Deploy to Vercel (Frontend)
        working-directory: ./frontend
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm

  # Backend Job
  backend:
    runs-on: ubuntu-latest
    needs: frontend  # Ensures frontend job runs first
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # - name: Set up Node.js (Backend)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.11.1'   # Update Node.js version here

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: |
          npm install

      - name: Run Linting (Backend)
        working-directory: ./backend
        run: |
          npm run lint

      - name: Run Tests (Backend)
        working-directory: ./backend
        run: |
          npm run test:coverage

      - name: Deploy to Render (Backend)
        working-directory: ./backend
        run: |
          render deploy --service backend --token ${{ secrets.RENDER_API_KEY }}
